[pytest]
# Tell pytest where your settings module actually is
DJANGO_SETTINGS_MODULE = DjangoWagtail.settings.dev

# Stop pytest-django from guessing the path incorrectly
django_find_project = false

# Add the root directory to your python path
pythonpath = .

# Optional: define where pytest should look for tests
python_files = tests.py test_*.py *_tests.py
