# Generated by Django 6.0.6 on 2026-06-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="quote",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
