# Generated by Django 6.0.6 on 2026-07-14 08:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_homepage_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="StreamField",
            field=wagtail.fields.StreamField(
                [("promoted", 2)],
                block_lookup={
                    0: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 500, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 0), ("body", 1)]],
                        {},
                    ),
                },
                default=[],
            ),
        ),
    ]
